version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: site_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        links:
          - php
        depends_on:
            - php
    php:
        container_name: site_php
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./code:/var/www/html
        links:
          - mysql
    mysql:
        image: mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: strongrootpassword
        container_name: site_mysql
        ports:
          - "3306:3306" 